#!/usr/bin/env zsh
if ! [[ -d ~/.icons ]]; then
mkdir ~/.icons
fi
cp -R delft/Delft-Purple-Darkest ~/.icons
cp -R delft/Delft-Purple-Dark ~/.icons
cp -R delft/Delft-Purple ~/.icons
cp -R delft/Delft ~/.icons
